services:
  bot-dev:
    build:
      context: .
      dockerfile: bot/Dockerfile
    image: budget_tracker:bot-dev
    container_name: budget_tracker_bot_dev
    environment:
      - ENV=dev
      - TZ=Asia/Singapore
    volumes:
      - .:/app
      - ./logs:/app/logs
    working_dir: /app
    networks:
      - wen-network

  bot-prod:
    image: wenyitan/budget_tracker_bot:latest
    container_name: budget_tracker_bot_prod
    environment:
      - ENV=prod
      - TZ=Asia/Singapore
    volumes:
      - ./logs:/app/logs
      - ./config/secrets.py:/app/config/secrets.py:ro
    working_dir: /app
    networks:
      - wen-network

  api-dev:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: budget_tracker:api-dev
    container_name: budget_tracker_api_dev
    ports:
      - "4000:4000"
    environment:
      - ENV=dev
      - FLASK_ENV=development
      - TZ=Asia/Singapore
      - APP=api
    volumes: 
      - .:/app
      - ./logs:/app/logs
    working_dir: /app
    restart: unless-stopped
    networks:
      - wen-network

  api-prod:
    build:
      context: .
      dockerfile: api/Dockerfile
    image: budget_tracker:api-prod
    container_name: budget_tracker_api_prod
    ports:
      - "5000:5000"
    environment:
      - ENV=prod
      - FLASK_ENV=production
      - TZ=Asia/Singapore
      - APP=api
    volumes: 
      - .:/app
      - ./logs:/app/logs
    working_dir: /app
    restart: unless-stopped
    networks:
      - wen-network

networks:
  wen-network:
    external: true