name: Python Backend CI (Manual Trigger)

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11.2'  # Adjust to match your project

    - name: Run tests using docker
      run: |
        pwd
        sh test.sh
