name: Python Backend CI (Manual Trigger)

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches: [main]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests using docker
      run: |
        pwd
        ./test.sh
