name: Python Backend CI

on:
  workflow_dispatch:  # Manual trigger only
  push:
    branches: [main, feature/mongodb_migration]

jobs:
  run-tests:
    runs-on: ubuntu-latest

    services:
      mongodb:
        image: mongo:5.0
        ports: 
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: root
          MONGO_INITDB_ROOT_PASSWORD: test_password
          MONGO_INITDB_DATABASE: test_db

    env:
      ENV: test
      TEST_ENV: github-actions
      JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
      ALLOWED_USERS: ${{ SECRETS.ALLOWED_USERS }}
      MONGO_URI: mongodb://root:test_password@localhost:27017
      MONGO_DB: test_db
      DATE_FORMAT: "%d-%b-%Y"
      PYTHONPATH: ${{ github.workspace }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Run tests using docker
      run: |
        pip install -r $PWD/tests/requirements_test.txt
        pytest -vvv --capture=tee-sys
