# name: Python Backend CI (Manual Trigger)

# on:
#   workflow_dispatch:  # Manual trigger only
#   push:
#     branches: [main]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - name: Checkout code
#       uses: actions/checkout@v3

#     - name: Set up Python
#       uses: actions/setup-python@v4
#       with:
#         python-version: '3.11.2'  # Adjust to match your project

#     - name: Create virtual environment
#       run: |
#         cd backend/
#         python -m venv venv
#         source venv/bin/activate
#         pip install --upgrade pip
#         pip install -r requirements.txt
    
#     - name: Set up SQLite db
#       run: |
#         cd backend/
#         python create_table.py

#     - name: Run tests
#       run: |
#         cd backend/
#         source venv/bin/activate
#         pytest services_test.py -vv
